language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
      - openjdk-8-jdk
services:
- mysql
before_script:
- cp .env.example .env
- cp src/main/resources/application-travis.properties src/main/resources/application.properties
- cp myFlywayConfig.properties.example myFlywayConfig.properties
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- mvn clean flyway:migrate -Dflyway.configFiles=myFlywayConfig.properties
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: BAoENWak9ZMgXkAawVDChwOg+F5DF+ROmBUmliaj2OR4vOom4Nn32tcVzj8SaAggvdFxSl2A+4iOtAJSFRoZHFyArFGgMGkIAXpeauNbM9IqlZ0WJl21xZ/YhpojbfZzcYNegeWa06abD/u3dWNd5jlE2eN04aG+iFzjufMpTLJXsJsaiwhiCUJB8/6K5nFO2cB9DzH4k2ChStXPBCCjfIIVNLBkQ0DPkKJnPpV60D+K6Z/imw4Y6oxPZVINfS7DYx0LJ2V1YVm/6xQRCgn/CyowawP3aCX2GCoX28xOI3tsdDUTvQFtn9bbz1i2j4RiJiMh4QfFsksWJKhw82GvQIyWsfVNfY5dzB+ofvxRTCCk8AfdhH7VjosXryhOQENOOTy5vgwxVtnE19JMKi2KiD+YTZt5wN1VD3j+87fo9rGy+P4MFvmqy59JV0u23taQJkny7dRU0LmEzk5sFu1R+okOfKYrGkBAuBGiOLExMR13SqR0vl/ZJYWG3eF6lDrrJvIWjM57bLDMuWy75sLmmug5nQenE/Xe84ZYsc3yCPpypOdVY/GPrC+Fw4O8R2Rdvc7AtiRx51CVusOzquS5UuGuq+1zX2cHVrgxDv6q+/0ItTJxQzLd5Xozke4D3u0hV+KHMu+bCmx4eGVK230uCr3/I6XRgVZc3bFX1Ys7P9o=
  - secure: iSRK+eQQkBVoLsms4DULw2lPXU2XqYm2Wliee8EA5E0jwtfu3nFEq4NPif+vzR86ZM8ziW1OlnjGIe716XaT4DyqgB3pg6s1iD7aP9165OdVxCbIqEeYJbA2V4ZxNK8n3NjTi3jW0KLgznV/WNp89vCsVTUAl26jzNvQELLi1B2nwLltYCOf3mEswnal+obGrqKfBUcQzbN9JvKHWxI4+VQnwmGUQ3YrttngNlcYbpuwgc/Ny5jguC+k9kDcwLhNffW68usFUnJtRpAlysVm7wyb6DrqKFK5AAJ7IxGpRv8o3QsrLPXQfQhJn1BeBwMmMT84Z3kG3YE/WcEKpY5sJUX97l+03BRt2VBlu5yW6U1+IQTWmARTqUmMWbz9q+BYbCjd8ifPAUHo9t60hhAxTLEpTPLnEHoU1c7avBN+lYvqnaRgsqzoVD5bwr37+N5oazzhrvcn5sacD093ssl9LJVrQYLhqWKgOcgWzNS9sRVjiunycYswAYQyKSMZdF2QPMampey0dLbLkEuzq1PlzjAcRA7OjYq3ysxP6pzP2QeOMwmtk8Ug6vMoRL5U6joZO0DqY60BEk5IOxLQ9mYSZ4Af3nkKrQiHEGRqOM0aEq5rrHHhCWgtfINTZoVRDuQSBQikWkll6oPmf7w0yLLrh+INRVnNL0WpjXvFv3gAtvk=
  - secure: pFCY7rmMuRqeJvitICGOmfqz9f906Ga8XbQ2eaJyhTJtCzGFarQ/978Ll6Rs+/8EXYHMqj5aXIs6qc41XNIpATszO0/dsPC5lnFzzPlRzRQQmYejt3MM4GW83iji4tZPnYyUfg08r+UPE8WhPjcVE2C3PB3Z0O1BHtiy+YlDKgwuuTh8iQktA41wpvYFz2XyiTpJyVDoc0L9Xv66FjVydmm6vRy6Lq/jZZ//wNtjFVvtyxhJxBBB+5eFgiZ2xYmdFSI9v71WYaKbQkds1rGYVSQAQxJoT7JIx0ZBczIvz6vH0bI+nFpDyXBnUtYPIwiz/QGjr1p5mVHFqQ8hqCW8vE5aelIzQjlC0WDupBD6aP2SH9XVu0NvgnUhL/OWEaoIlE7wq7hyFkmieQmLUj34mLKoMTA/k6GD0dUQxaU8aCbROmO5Vl3OD5ZoZDmmGFtvUoW5F1UyUQnbma3JvSZZoBC35YNTfC4PAOuFxQgOiSR2EhgiAXYLKtxLpSOd9r1rmoL/tjolir8Yu5sHLbSJPIc5reY2V5fyzJVAXyJBKULcLoqMrfEmTgcPVv9y/M9UKIcys2+dWiOE44p/LPbxV0M5fBh3PvQdvPYldGtYYNEeplDNmnBNH8ywBw8P4cmwRQkamvJN1x4v86/ym4VgTt5BYqfCIshlVborh8Bp9TE=
