language: java
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: LT/lDPiCpUxV/dJ+44lW/0dSYpf8+xYFD/CrGiR4mB/K68BXbg00sd+2UJ8cp21GnVvS5KFP1Ez1gwm1osSu6HNGpmQ2CnIcnpjhfJRSC+PYqKz4UgkmI8DVVXeXz8xeS8ojK3aqOZq+7OqEPqqk3Y2Q84CRlfYRzG9Um/UlTPtu4KJF4llT23kAz2Zu8fikST8zx6m4vgSQZRYbXbAUbptGrpomb/Yt5aujyRSQ8mbSpL0a0zfGIpQeWyreSCJi565GKbnFIM8XZW3poYWxGrXs8Jis6ymjhX1WZ5Mp1+9o3kGM07A1rb3PqMNFOhjwPxreS0DJRzt+4l7U2Izu1gGXnoYgjKLgvk4rISokiKQGIemVIh5HigT3sqwS8BOiBxKeWoMcZo6i+b4f5lrhU+JbsUjbG+1pal5ujjYZJflQhGk68QvU/gweJ+uEoQJF62hnOFEwoyRE8NiYkAojp7klj97ugR0AUPUYpZY4iD6uAnC+Gbn8npn1lK1jeqWsC9fv99CcAbGBTKNd0Rv99iPu7ZD7JPJFqZ3bQ5Y8waMqfK3RS2MKjHw+NhNEIjYjmbmad9FSj28UXyp+3aLRIY0CL7Z1+5TBsZJYOSnOJ33QrEp6g3XTncczpsVZwMQkV4Szw/SeS6BUsr/IOaSZzPoFyTWLqLkBpk+5nhISG/0=
