language: java

services:
- mysql

before_script:
- cp .env.example .env
- cp myFlywayConfig.properties.example myFlywayConfig.properties
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- mvn clean flyway:migrate -Dflyway.configFile=myFlywayConfig.properties

after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: BAoENWak9ZMgXkAawVDChwOg+F5DF+ROmBUmliaj2OR4vOom4Nn32tcVzj8SaAggvdFxSl2A+4iOtAJSFRoZHFyArFGgMGkIAXpeauNbM9IqlZ0WJl21xZ/YhpojbfZzcYNegeWa06abD/u3dWNd5jlE2eN04aG+iFzjufMpTLJXsJsaiwhiCUJB8/6K5nFO2cB9DzH4k2ChStXPBCCjfIIVNLBkQ0DPkKJnPpV60D+K6Z/imw4Y6oxPZVINfS7DYx0LJ2V1YVm/6xQRCgn/CyowawP3aCX2GCoX28xOI3tsdDUTvQFtn9bbz1i2j4RiJiMh4QfFsksWJKhw82GvQIyWsfVNfY5dzB+ofvxRTCCk8AfdhH7VjosXryhOQENOOTy5vgwxVtnE19JMKi2KiD+YTZt5wN1VD3j+87fo9rGy+P4MFvmqy59JV0u23taQJkny7dRU0LmEzk5sFu1R+okOfKYrGkBAuBGiOLExMR13SqR0vl/ZJYWG3eF6lDrrJvIWjM57bLDMuWy75sLmmug5nQenE/Xe84ZYsc3yCPpypOdVY/GPrC+Fw4O8R2Rdvc7AtiRx51CVusOzquS5UuGuq+1zX2cHVrgxDv6q+/0ItTJxQzLd5Xozke4D3u0hV+KHMu+bCmx4eGVK230uCr3/I6XRgVZc3bFX1Ys7P9o=